spring:
  application:
    name: ticketbox
  profiles:
    active: api

  datasource:
    url: jdbc:postgresql://ep-snowy-firefly-azpxmhww-pooler.c-3.ap-southeast-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_xS7QFDkMXYC5&sslmode=require&channelBinding=require
    username: ${DB_USER:neondb_owner}
    password: ${DB_PASSWORD:npg_xS7QFDkMXYC5}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    baseline-on-migrate: true
    repair-on-migrate: true
    locations: classpath:db/migration

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      host: ${REDIS_HOST:moving-roughy-76529.upstash.io}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:gQAAAAAAASrxAAIgcDI2M2QzMDRhMDA1Y2E0YmU2ODM1MDAxYWJmM2E3MTY2Mw}
      ssl:
        enabled: ${REDIS_SSL:true}

  rabbitmq:
    host: ${RABBITMQ_HOST:fuji.lmq.cloudamqp.com}
    virtual-host: ${RABBITMQ_VHOST:ykxlsjhy}
    port: ${RABBITMQ_PORT:5671}
    username: ${RABBITMQ_USER:ykxlsjhy}
    password: ${RABBITMQ_PASSWORD:N0LiNWaBQARTfuK-r-B4DsKYPazMalm7}
    ssl:
      enabled: ${RABBITMQ_SSL:true}

  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:quocthailenguyen41@gmail.com}
    password: ${MAIL_PASSWORD:krmaawatipuhtlio}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  access-token: fbf31e0e58fa369c5ad1909f9d013ee03fb267e767aedff8b2fff6cc9b6dc9f6
  access-token-expiration: 900000 # 15 mins in ms
  refresh-token: ccd0c7a7b168a1fe1a719e0afa3ad66b0a2afb6fba8bf0f877faa1e855349a66
  refresh-token-expiration: 2592000000 # 30 days in ms
